default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recruitment_app_development

test:
  <<: *default
  database: recruitment_app_test

production:
  <<: *default
  database: recruitment_app_production
